- hosts: all
  roles:
    - common

#- hosts: ben-kafka-server
#  roles:
#    - kafka-server

- hosts: metadata-db-prod
  roles:
     - metadata-server


- hosts: haste-gateway.benblamey.com
  roles:
     - gateway