- name: Add mongo ppa key
  become: yes
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=9DA31620334BD75D9DCB49F368818C72E52529D4
    state=present

- name: Add mongo sources list (Bionic/18)
  become: yes
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-4.0.list
    state=present
    create=yes

- name: Install mongodb
  become: yes
  apt: name=mongodb-org state=latest update_cache=yes


#By default, MongoDB instance stores:
#its data files in /var/lib/mongodb
#its log files in /var/log/mongodb
#/etc/mongod.conf

- name: mongod config
  become: true
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf

# TODO: restart only in case of config change
- name: restart mongodb
  become: true
  service:
    name: mongod
    state: restarted
# If this fails, check: $ journalctl -u mongod

- name: include creds from encrypted dir
  include_vars:
    file: enc/vars-hpc2n.yml
    name: enc

- name: install python3 pip (needed to install pymongo)
  become: true
  package:
    name: python3-pip
    update-cache: yes

- name: Install pymongo (needed for 'mongodb_user')
  pip:
    executable: pip3
    name: pymongo

# Note: we need to temporarily disable authentication so we can get in and add the first user! (see Readme)
#- name: Create MongoDB adminstrator. (this fails when auth is turned on)
#  mongodb_user:
#    database: admin
#    name: "{{ enc.mongodb_admin_username }}"
#    password: "{{ enc.mongodb_admin_password }}"
#    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
#    state: present

# Now we use the credentials we just created to setup the other users:
- name: Create MongoDB user
  mongodb_user:
    login_database: admin
    login_user: "{{ enc.mongodb_admin_username }}"
    login_password: "{{ enc.mongodb_admin_password }}"
    database: streams
    name: "{{ enc.mongodb_user_username }}"
    password: "{{ enc.mongodb_user_password }}"
    state: present
    roles: [ { role: "readWrite", db: "streams" } ]